SET storage_engine=INNODB;

-- Dropping tables: pay attention to order for FK
DROP TABLE IF EXISTS T_RING_CONTENT;
DROP TABLE IF EXISTS T_RELATION;
DROP TABLE IF EXISTS T_RING;
DROP TABLE IF EXISTS T_USER;

CREATE TABLE T_USER (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(255) UNIQUE NOT NULL,
    `ENC_PASSWORD` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`ID`)
);

CREATE TABLE T_RING (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT UNSIGNED NOT NULL,
    `TIMESTAMP` TIMESTAMP NOT NULL,

    PRIMARY KEY (`ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES T_USER(`ID`) ON DELETE CASCADE
);

CREATE TABLE T_RELATION (
    `FOLLOWER_ID` BIGINT UNSIGNED NOT NULL,
    `FOLLOWED_ID` BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY (`FOLLOWER_ID`, `FOLLOWED_ID`),
    FOREIGN KEY (`FOLLOWER_ID`) REFERENCES T_USER(`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`FOLLOWED_ID`) REFERENCES T_USER(`ID`) ON DELETE CASCADE
);

CREATE TABLE T_RING_CONTENT (
    `ID` BIGINT UNSIGNED NOT NULL, -- ringId
    `CONTENT` VARCHAR(255) NOT NULL,
    
    PRIMARY KEY (`ID`),
    FULLTEXT INDEX `ft_ring_content` (`CONTENT` ASC)
) ENGINE MYISAM;

/*
-- We could use a trigger to act as a FK on delete cascade.
-- We cannot use FK from a InnoDB table towards a MyISAM one.
DELIMITER $$

CREATE TRIGGER `TR_DELETE_RING_CONTENT`
AFTER DELETE ON `T_RING`
FOR EACH ROW
BEGIN
    DELETE FROM T_RING_CONTENT 
        WHERE T_RING_CONTENT.ID = OLD.ID;
END

$$

DELIMITER ;
*/

-- POPULATE WITH SOME DATA
INSERT INTO T_USER (ID, USERNAME, ENC_PASSWORD) VALUES (1, 'user1', '18aab3392031eab3c193e9f24ed43897'); -- Pass=user1
INSERT INTO T_USER (ID, USERNAME, ENC_PASSWORD) VALUES (2, 'user2', 'b1f4cdf12f5cfc7b8995e7c6a925d456'); -- Pass=user2

INSERT INTO T_RELATION (FOLLOWER_ID, FOLLOWED_ID) VALUES (1, 2);

INSERT INTO T_RING (ID, USER_ID, TIMESTAMP) VALUES (1, 1, '2010-09-12 10:10:10');
INSERT INTO T_RING (ID, USER_ID, TIMESTAMP) VALUES (2, 1, '2010-10-11 10:10:10');
INSERT INTO T_RING (ID, USER_ID, TIMESTAMP) VALUES (3, 1, '2010-11-09 10:10:10');
INSERT INTO T_RING (ID, USER_ID, TIMESTAMP) VALUES (4, 2, '2011-09-12 10:10:10');
INSERT INTO T_RING (ID, USER_ID, TIMESTAMP) VALUES (5, 2, '2011-10-11 10:10:10');
INSERT INTO T_RING (ID, USER_ID, TIMESTAMP) VALUES (6, 2, '2011-11-09 10:10:10');

INSERT INTO T_RING_CONTENT (ID, CONTENT) VALUES (1, 'Ring 1 User 1');
INSERT INTO T_RING_CONTENT (ID, CONTENT) VALUES (2, 'Ring 2 User 1');
INSERT INTO T_RING_CONTENT (ID, CONTENT) VALUES (3, 'Ring 3 User 1');
INSERT INTO T_RING_CONTENT (ID, CONTENT) VALUES (4, 'Ring 1 User 2');
INSERT INTO T_RING_CONTENT (ID, CONTENT) VALUES (5, 'Ring 2 User 2');
INSERT INTO T_RING_CONTENT (ID, CONTENT) VALUES (6, 'Ring 3 User 2');

